---
title: "Documentation_variables"
format: pdf
editor: visual
---

## Documentation variables d'intérets :

+--------------------------------+--------------------+-------------------+----------------------------------------------------------------------+
| Nom original                   | Nom dans le code   | Début de la série | Code BDF                                                             |
+================================+====================+===================+======================================================================+
| Dette des Ménages, en % du PIB | endettement_menage | "1999-03-31"      | CNFSI.Q.S.FR.W0.S1M.S1.N.L.LE.DETT.T.\_Z.XDC_R_B1GQ_CY.\_T.S.V.N.\_T |
+--------------------------------+--------------------+-------------------+----------------------------------------------------------------------+
| Dette des SNF, en % du PIB     | endettement_snf    | "1999-03-31"      | CNFSI.Q.S.FR.W0.S11.S1.C.L.LE.DETT.T.\_Z.XDC_R_B1GQ_CY.\_T.S.V.N.\_T |
+--------------------------------+--------------------+-------------------+----------------------------------------------------------------------+

## Documentation data Banque de France :

+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Nom original                                                                                                               | Nom dans le code    | Début de la série (post emprunt ménage et snf) | Code BDF                                                               |
+============================================================================================================================+=====================+================================================+========================================================================+
| France, Taux d'inflation                                                                                                   | inflation           |                                                | ICP.M.FR.N.000000.4.ANR                                                |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Taux de l'emprunt phare à 10 ans - France                                                                                  | Taux_long           |                                                | FM.M.FR.EUR.FR2.BB.FR10YT_RR.YLD                                       |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Taux de chômage au sens du BIT - Ensemble - France métropolitaine - Données CVS                                            | chomage             |                                                | STS.Q.FR.S.UNEH.RTT000.4.000                                           |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Crédits nouveaux à l'habitat des particuliers, à plus d'un an, taux d'intérêt annuel                                       | credit_aplusunan    | "2003-03-31"                                   | MIR1.M.FR.B.A22.K.R.A.2254U6.EUR.N                                     |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Octroi de crédits à l'habitat                                                                                              | octroi_credit       | "2003-03-31"                                   | BLS.Q.FR.ALL.Z.H.H.B3.ST.S.FNET                                        |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Demande de crédits à l'habitat                                                                                             | demande_credit      | "2002-12-31"                                   | BLS.Q.FR.ALL.Z.H.H.B3.ZZ.D.FNET                                        |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Coût de financement des SNF, taux en %                                                                                     | Taux_snf            | "2010-12-31"                                   | MIR1.M.FR.B.AT0.A.R.A.2240U6.EUR.N                                     |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Durée moyenne des crédits immobiliers aux particuliers                                                                     | Duree_immo          | "2004-01-31"                                   | MIR1.Q.FR.R.A22FRX.A.R.A.2254FR.EUR.N                                  |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Moyenne des taux effectifs (sens étroit) des crédits immobiliers aux particuliers                                          | Taux_immo           | "2004-03-31"                                   | MIR1.Q.FR.R.A22FRX.A.D.A.2254FR.EUR.N                                  |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Salaires négociés France                                                                                                   | salaires            | "2006-01-31"                                   | STS.Q.FR.N.INWR.000000.2.ANR                                           |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Indice des prix des logements anciens - France métropolitaine - Ensemble - Base 100 en moyenne annuelle 2015 - Série brute | prix_logement       |                                                | RPP.Q.FR.N.ED.00.1.00                                                  |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Taux d’épargne des ménages - France, taux trimestriel, CVS                                                                 | epargne             | "2012-03-31"                                   | CNFSI.Q.Y.FR.W0.S1M.S1.N.B.B8G.\_Z.\_Z.\_Z.XDC_R_B6G_S1M.\_T.S.V.N.\_T |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Agrégats monétaires Zone euro, M3 \[moyenne mobile 3 mois du glissement annuel\] (CVS-CJO)                                 | M3                  |                                                | BSI.M.U2.Y.V.M30.X.I.U2.2300.Z01.V                                     |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+
| Indicateur ajusté et lissé mensuel des anticipations d'inflation francaise issu de la presse                               | inflation_anticipée | "2004-01-31"                                   | PAI.M.FR.N.PR.\_Z.INPR03.TX                                            |
+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------------------------------------+------------------------------------------------------------------------+

+----------------+
|                |
+----------------+
